### ISSUE TITLE
 Bump bindings to the latest versions of native libraries

### ISSUE THREAD

**Issue by kcrg** [JosueDM94/Xamarin.Google.Maps.Utils#7]
Hi!

I saw recently some commits that bumps Android and iOS native libraries to old versions e.g. [android-maps-utils](https://github.com/googlemaps/android-maps-utils) to 1.2.0 while 2.4.0 is latest.

Is there a reason why not bump these libs at once to latest?
I'd love to use new API's like ability to change animation duration of merging markers from latest lib version. https://github.com/googlemaps/android-maps-utils/releases/tag/v2.4.0

If you want I can send PR's for this also adding support for .NET for Android/iOS (MAUI).

**Comment by JosueDM94** [comment]
Hello, 

Yes, the main idea is to bump this library to the latest version of both native libraries, and also support .Net Maui(System.Android & System.iOS), but not at once. At this moment I'm bumping one by one because if any other library uses the native references and the latest version doesn't contain a specific class will throw a class not found exception.

But for sure that I'll continue updating and supporting this library.

**Comment by kcrg** [comment]
I ain't buying that. If there is breaking changes in latest native lib, devs should adjust their code to address that. There is no point to bind every single version. Waste of time in my opinion. What if they change implementation of some methods in each release? I should adjust my code for each release or just once for latest?

If u want my PRs I'd love to help.
